$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: ig-classifier-endpoint
model:
  path: ./model
code_configuration:
  code: ./model/onlinescoring
  scoring_script: score.py
environment:
  conda_file: ./model/environment/conda.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS3_v2
instance_count: 1