$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: ig-classifier-env
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: ./model/environment/conda.yml